apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: myweb-service
spec:
  selector:
    prod: web_env
  type: NodePort
  ports:
    - nodePort: 31001
      port: 80
      targetPort: 80
